apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: shiki
spec:
  enabled: true
  requires: ">=2.17.0"
  author:
    name: Halo
    website: https://github.com/halo-dev
  logo: logo.svg
  homepage: https://github.com/halo-sigs/plugin-shiki#readme
  repo: https://github.com/halo-sigs/plugin-shiki
  issues: https://github.com/halo-sigs/plugin-shiki/issues
  displayName: "Shiki 代码高亮"
  description: "提供对 Shiki 的集成，扩展默认编辑器代码块，支持在内容页高亮显示代码块。"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-sigs/plugin-shiki/blob/main/LICENSE"